language: scala
sudo: true
scala:
  - 2.12.7
jdk: openjdk8

services:
  - postgresql

#branches:
  #only:
    #- master

dist: xenial
#addons:
  #apt:

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gcc make libtool libhwloc-dev libx11-dev libxt-dev libedit-dev libical-dev ncurses-dev perl postgresql-server-dev-9.6 python-dev tcl-dev tk-dev swig libexpat-dev libssl-dev libxext-dev libxft-dev autoconf automake

install:
  - dev/install_deps.sh

script:
  - travis_wait dev/check_build.sh
