language: scala
scala:
  - 2.12.7
jdk: oraclejdk8

branches:
  only:
    - master

services:
  - docker

install: true

script:
  - travis_wait ./check_build.sh

deploy:
    skip_cleanup: true
    provider: script
    script: cd /tmp/spark/resource-managers/pbs && ./deploy_docker.sh
