language: scala
scala:
   - 2.11.12
jdk: oraclejdk8

before_install:
  - git clone https://github.com/apache/spark
  - cd spark/
  - git checkout 960af63

cache:
  directories:
    - $HOME/.sbt
    - $HOME/.m2

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git resource-managers/pbs
  - cd resource-managers/pbs && git checkout -qf $TRAVIS_COMMIT && cd ../..
  - git am resource-managers/pbs/patches/*
  - export MAVEN_SKIP_RC=1
  - travis_wait build/mvn -T 4 -q -DskipTests -Pkinesis-asl -Ppbs -Pmesos -Pkubernetes -Pyarn -Phive -Phive-thriftserver install

script:
  - cp resource-managers/pbs/dev/lint-java dev/lint-java
  - dev/lint-java
